#define MAX_STRING_LENGTH 256

#define IDI_APPICON 201

#define IDS_USAGE 0
#define IDS_LOADING 1
#define IDS_SUCCESS 2
#define IDS_FAILURE 3
#define IDS_INSTALL 4
#define IDS_UNINSTALL 5
#define IDS_CLOSE 6
#define IDS_TIMESPEC 7
#define IDS_TIMEUNDEF 8

#define IDD_LOADER 101
#define IDC_OK 1
#define IDC_DLGICON 12
#define IDC_MESSAGE 8
#define IDC_PROGRESS 10
